In [1]:
import pandas as pd
df_cust_orders=pd.read_csv('/content/customer_orders.csv')
df_pizza_names=pd.read_csv('/content/pizza_names.csv')
df_recipes=pd.read_csv('/content/pizza_recipes.csv')
df_pizza_toppings=pd.read_csv('/content/pizza_toppings.csv')
df_runner_orders=pd.read_csv('/content/runner_orders.csv')
df_runners=pd.read_csv('/content/runners.csv')

In [7]:
df_cust_orders.head()

   order_id  customer_id  pizza_id exclusions extras           order_time
0         1          101         1        NaN    NaN  2020-01-01 18:05:02
1         2          101         1        NaN    NaN  2020-01-01 19:00:52
2         3          102         1        NaN    NaN  2020-01-02 23:51:23
3         3          102         2        NaN    NaN  2020-01-02 23:51:23
4         4          103         1          4    NaN  2020-01-04 13:23:46

In [8]:
df_pizza_names.head()

   pizza_id  pizza_name
0         1  Meatlovers
1         2  Vegetarian

In [9]:
df_recipes.head()

   pizza_id                 toppings
0         1  1, 2, 3, 4, 5, 6, 8, 10
1         2       4, 6, 7, 9, 11, 12

In [10]:
df_pizza_toppings.head()

   topping_id topping_name
0           1        Bacon
1           2    BBQ Sauce
2           3         Beef
3           4       Cheese
4           5      Chicken

In [11]:
df_runners.head()

   runner_id registration_date
0          1        2021-01-01
1          2        2021-01-03
2          3        2021-01-08
3          4        2021-01-15

In [12]:
df_runner_orders.head()

   order_id  runner_id          pickup_time distance    duration cancellation
0         1          1  2020-01-01 18:15:34     20km  32 minutes          NaN
1         2          1  2020-01-01 19:10:54     20km  27 minutes          NaN
2         3          1  2020-01-03 00:12:37   13.4km     20 mins          NaN
3         4          2  2020-01-04 13:53:03     23.4          40          NaN
4         5          3  2020-01-08 21:10:57       10          15          NaN

## Part A - Pizza Metrics

## 1. How many pizzas were ordered?

In [14]:
df_cust_orders['customer_id'].count()

14

## 2.How many unique customer orders were made?

In [16]:
df_cust_orders['customer_id'].nunique()

5

## 3. How many successful orders were delivered by each runner?

In [21]:
df_x=df_runner_orders.copy()
df_x=df_x[df_x['cancellation'].isna()]
df_x.groupby(['runner_id'])['order_id'].count()

runner_id
1    4
2    3
3    1
Name: order_id, dtype: int64

## 4 How many of each type of pizza was delivered?

In [22]:
df_merge=pd.merge(df_cust_orders,df_pizza_names, on="pizza_id")
df_merge

,order_id,customer_id,pizza_id,exclusions,extras,order_time,pizza_name
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,Meatlovers
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,Meatlovers
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,Meatlovers
3,4,103,1,4,NaN,2020-01-04 13:23:46,Meatlovers
4,4,103,1,4,NaN,2020-01-04 13:23:46,Meatlovers
5,5,104,1,NaN,1,2020-01-08 21:00:29,Meatlovers
6,8,102,1,NaN,NaN,2020-01-09 23:54:33,Meatlovers
7,9,103,1,4,"1, 5",2020-01-10 11:22:59,Meatlovers
8,10,104,1,NaN,NaN,2020-01-11 18:34:49,Meatlovers
9,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,Meatlovers
10,3,102,2,NaN,NaN,2020-01-02 23:51:23,Vegetarian
11,4,103,2,4,NaN,2020-01-04 13:23:46,Vegetarian
12,6,101,2,NaN,NaN,2020-01-08 21:03:13,Vegetarian
13,7,105,2,NaN,1,2020-01-08 21:20:29,Vegetarian

In [23]:
df_merge['pizza_name'].value_counts()

Meatlovers    10
Vegetarian     4
Name: pizza_name, dtype: int64

## 5 How many Vegetarian and Meatlovers were ordered by each customer?

In [32]:
df_merge.groupby(['customer_id','pizza_name'])['pizza_name'].count().to_frame("pizza_count").reset_index()

   customer_id  pizza_name  pizza_count
0          101  Meatlovers            2
1          101  Vegetarian            1
2          102  Meatlovers            2
3          102  Vegetarian            1
4          103  Meatlovers            3
5          103  Vegetarian            1
6          104  Meatlovers            3
7          105  Vegetarian            1

## 6 What was the maximum number of pizzas delivered in a single order?

In [33]:
df_runner_orders

,order_id,runner_id,pickup_time,distance,duration,cancellation
0,1,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,4,2,2020-01-04 13:53:03,23.4,40,NaN
4,5,3,2020-01-08 21:10:57,10,15,NaN
5,6,3,NaN,NaN,NaN,Restaurant Cancellation
6,7,2,2020-01-08 21:30:45,25km,25mins,NaN
7,8,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
8,9,2,NaN,NaN,NaN,Customer Cancellation
9,10,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [34]:
df_cust_orders

    order_id  customer_id  pizza_id exclusions extras           order_time
0          1          101         1        NaN    NaN  2020-01-01 18:05:02
1          2          101         1        NaN    NaN  2020-01-01 19:00:52
2          3          102         1        NaN    NaN  2020-01-02 23:51:23
3          3          102         2        NaN    NaN  2020-01-02 23:51:23
4          4          103         1          4    NaN  2020-01-04 13:23:46
5          4          103         1          4    NaN  2020-01-04 13:23:46
6          4          103         2          4    NaN  2020-01-04 13:23:46
7          5          104         1        NaN      1  2020-01-08 21:00:29
8          6          101         2        NaN    NaN  2020-01-08 21:03:13
9          7          105         2        NaN      1  2020-01-08 21:20:29
10         8          102         1        NaN    NaN  2020-01-09 23:54:33
11         9          103         1          4   1, 5  2020-01-10 11:22:59
12        10          104         1        NaN    NaN  2020-01-11 18:34:49
13        10          104         1       2, 6   1, 4  2020-01-11 18:34:49

In [35]:
df_merge=pd.merge(df_cust_orders,df_runner_orders,on="order_id")
df_merge

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN
8,6,101,2,NaN,NaN,2020-01-08 21:03:13,3,NaN,NaN,NaN,Restaurant Cancellation
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
11,9,103,1,4,"1, 5",2020-01-10 11:22:59,2,NaN,NaN,NaN,Customer Cancellation
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [39]:
df_merge=df_merge[df_merge['cancellation'].isna()]

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [43]:
df_merge=df_merge['order_id'].value_counts().to_frame("count")

In [46]:
df_merge.iloc[0]

count    3
Name: 4, dtype: int64

## 7. For each customer, how many delivered pizzas had at least 1 change and how many had no changes?

In [48]:
df_merge=pd.merge(df_cust_orders,df_runner_orders,on="order_id")
df_merge=df_merge[df_merge['cancellation'].isna()]
df_merge

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [57]:
df_no_change=df_merge[(df_merge['exclusions'].isna()) & (df_merge['extras'].isna())]
df_no_change

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [58]:
df_no_change.groupby(['customer_id'])['order_id'].count()

customer_id
101    2
102    3
104    1
Name: order_id, dtype: int64

In [59]:
df_change=df_merge[(df_merge['exclusions'].notna()) | (df_merge['extras'].notna())]
df_change

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [61]:
df_change.groupby(['customer_id'])['order_id'].count()

customer_id
103    3
104    2
105    1
Name: order_id, dtype: int64

## 8. How many pizzas were delivered that had both exclusions and extras?

In [62]:
df_merge=pd.merge(df_cust_orders,df_runner_orders,on="order_id")
df_merge=df_merge[df_merge['cancellation'].isna()]
df_merge

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [63]:
df_change=df_merge[(df_merge['exclusions'].notna()) & (df_merge['extras'].notna())]
df_change

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [65]:
df_change[['order_id','customer_id','pizza_id','exclusions','extras']]

    order_id  customer_id  pizza_id exclusions extras
13        10          104         1       2, 6   1, 4

## 9.What was the total volume of pizzas ordered for each hour of the day?

it makes more sense to perform analytics on those orders which were not cancelled.

In [104]:
df_merge=pd.merge(df_cust_orders,df_runner_orders,on="order_id")
df_merge=df_merge[df_merge['cancellation'].isna()]
df_merge

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [105]:
df_merge['order_time']=pd.to_datetime(df_merge['order_time'])

In [106]:
df_merge['date']=df_merge['order_time'].dt.date
df_merge['time']=df_merge['order_time'].dt.time
df_merge['hour']=df_merge['order_time'].dt.hour

In [107]:
df_x=df_merge.groupby(['date','hour'])['hour'].count().to_frame("count_hour").reset_index()

In [108]:
df_x['vol']=df_x['count_hour']/sum(df_x['count_hour'])*100
df_x

         date  hour  count_hour        vol
0  2020-01-01    18           1   8.333333
1  2020-01-01    19           1   8.333333
2  2020-01-02    23           2  16.666667
3  2020-01-04    13           3  25.000000
4  2020-01-08    21           2  16.666667
5  2020-01-09    23           1   8.333333
6  2020-01-11    18           2  16.666667

##10.What was the volume of orders for each day of the week?

In [124]:
df_merge=pd.merge(df_cust_orders,df_runner_orders,on="order_id")
#df_merge=df_merge[df_merge['cancellation'].isna()]
df_merge

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN
8,6,101,2,NaN,NaN,2020-01-08 21:03:13,3,NaN,NaN,NaN,Restaurant Cancellation
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN
11,9,103,1,4,"1, 5",2020-01-10 11:22:59,2,NaN,NaN,NaN,Customer Cancellation
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN

In [125]:
df_merge['order_time']=pd.to_datetime(df_merge['order_time'])
df_merge['date']=df_merge['order_time'].dt.date
df_merge['time']=df_merge['order_time'].dt.time
df_merge['day_of_week']=df_merge['order_time'].dt.dayofweek

In [126]:
df_merge

,order_id,customer_id,pizza_id,exclusions,extras,order_time,runner_id,pickup_time,distance,duration,cancellation,date,time,day_of_week
0,1,101,1,NaN,NaN,2020-01-01 18:05:02,1,2020-01-01 18:15:34,20km,32 minutes,NaN,2020-01-01,18:05:02,2
1,2,101,1,NaN,NaN,2020-01-01 19:00:52,1,2020-01-01 19:10:54,20km,27 minutes,NaN,2020-01-01,19:00:52,2
2,3,102,1,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN,2020-01-02,23:51:23,3
3,3,102,2,NaN,NaN,2020-01-02 23:51:23,1,2020-01-03 00:12:37,13.4km,20 mins,NaN,2020-01-02,23:51:23,3
4,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN,2020-01-04,13:23:46,5
5,4,103,1,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN,2020-01-04,13:23:46,5
6,4,103,2,4,NaN,2020-01-04 13:23:46,2,2020-01-04 13:53:03,23.4,40,NaN,2020-01-04,13:23:46,5
7,5,104,1,NaN,1,2020-01-08 21:00:29,3,2020-01-08 21:10:57,10,15,NaN,2020-01-08,21:00:29,2
8,6,101,2,NaN,NaN,2020-01-08 21:03:13,3,NaN,NaN,NaN,Restaurant Cancellation,2020-01-08,21:03:13,2
9,7,105,2,NaN,1,2020-01-08 21:20:29,2,2020-01-08 21:30:45,25km,25mins,NaN,2020-01-08,21:20:29,2
10,8,102,1,NaN,NaN,2020-01-09 23:54:33,2,2020-01-10 00:15:02,23.4 km,15 minute,NaN,2020-01-09,23:54:33,3
11,9,103,1,4,"1, 5",2020-01-10 11:22:59,2,NaN,NaN,NaN,Customer Cancellation,2020-01-10,11:22:59,4
12,10,104,1,NaN,NaN,2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN,2020-01-11,18:34:49,5
13,10,104,1,"2, 6","1, 4",2020-01-11 18:34:49,1,2020-01-11 18:50:20,10km,10minutes,NaN,2020-01-11,18:34:49,5

In [128]:
df_x=df_merge.groupby(['day_of_week'])['order_id'].count().to_frame("count")

In [131]:
df_x['vol']=df_x['count']/sum(df_x['count'])*100
df_x

             count        vol
day_of_week
2                5  35.714286
3                3  21.428571
4                1   7.142857
5                5  35.714286